on:
  schedule: 
    - cron:  "0 1 * * *" 
  workflow_dispatch:


name: Update data

jobs:
  updade-data:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # that installs R on the machine
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # The R version to download (if necessary) and use.
          r-version: '4.3.2'
          # uses the RStudio Package Manager
          use-public-rspm: true

      # Install packages
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::stringr 
            any::rvest

      # to access the code inside our repository
      - name: Check out repository
        uses: actions/checkout@v4

      # exec script
      - name: Import data
        run: Rscript -e 'source("scraping.R")'

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW 

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: data updated ${{ env.NOW }}

  deploy-shiny:
    needs: updade-data
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # that installs R on the machine
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # The R version to download (if necessary) and use.
          r-version: '4.3.2'
          # uses the RStudio Package Manager
          use-public-rspm: true

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("rsconnect")'
          Rscript -e 'install.packages("shiny")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("stringr")'
          Rscript -e 'install.packages("zoo")'
          Rscript -e 'install.packages("plotly")'
          Rscript -e 'install.packages("lubridate")'
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("rvest")'
          Rscript -e 'install.packages("shinyjs")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # to access the code inside our repository
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Render Quarto Project
        run: quarto render dash.qmd

      # deploy
      - name: deploy
        run: Rscript -e 'source("deploy.R")'
        env:
          NAME: ${{ vars.NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
